steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/rakna-ai-model/complaint-class-api
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/rakna-ai-model/complaint-class-api
images:
  - gcr.io/rakna-ai-model/complaint-class-api
